site_name: Målarkitektur datadeling Digitial hjemmeoppfølging
repo_url: https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging
repo_name: Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging
nav:
    - Innledning: index.md
    - Sammendrag: Sammendrag.md
    - Begreper: Begreper.md
    - Arkitekturprinsipper: Arkitekturprinsipper.md
    - Kontekst for målarkitekturen: 
      - Sammenheng med annet arbeid: Kontekst.md
      - Målbilde for DHO: Overordnet-maalbilde.md
    - Overordnet behovsbilde digital samhandling DHO: Behovsbilde.md
    - Juridiske rammebetingelser: Juridiske-rammebetingelser.md
    - Målarkitektur samhandling DHO: Malarkitektur-samhandling.md
    - Konsepter realisering: Konsepter-realisering.md
    - Referanser: Referanser.md
    - Tilbakemeldinger og innspill: Tilbakemeldinger-innspill.md
    - Statusinformasjon: https://direktoratet-for-e-helse.github.io/Common-metadata/
theme:
  name: material
  logo: logo/ehelse-hvit.svg
  #custom_dir: material/.overrides
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/git-alt
  favicon: logo/ehelse-hvit.png
markdown_extensions:
  - mdx_truly_sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  #icon:
  #  logo: logo