site_name: Målarkitektur datadeling digital hjemmeoppfølging
repo_url: https://github.com/Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging
repo_name: Direktoratet-for-e-helse/Malarkitektur-digital-hjemmeoppfolging
site_author: Direktoratet for e-helse
nav:
    - Sammendrag: 
      - index.md
    - Innledning: 
      - innledning/index.md
    - Behov: 
      - behov/index.md
    - Juridiske vurderinger:
      - juridisk/index.md
    - Krav og anbefalinger: 
      - kravoganbefalinger/index.md
    - Referanser: 
      - referanser/index.md
    - Vedlegg:
      - vedlegg/index.md
      - Begreper: vedlegg/Begreper.md
      - Arkitekturprinsipper: vedlegg/Arkitekturprinsipper.md
      - Detaljert behovsbilde: vedlegg/Detaljert-behovsbilde.md
      - Vurdering av konsepter for realisering: vedlegg/Konsepter-realisering.md
      - Eksempler fra utprøving: vedlegg/Eksempler.md
      - Anbefalte tiltak: vedlegg/Anbefalte-tiltak.md
      - Målbilde for DHO og velferdsteknologiprogrammet: vedlegg/Overordnet-maalbilde.md
      - Semantisk samhandlingsevne: vedlegg/Semantisk-samhandling.md
      - Juridisk vurdering av intern kopi: vedlegg/Juridisk-intern-kopi.md
      - Datadeling - slå opp - metamodell: vedlegg/Organisatorisk-sla-opp.md
      - Hva er kapabiliteter - metamodell: vedlegg/Kapabiliteter.md
      - Informasjonstjeneste - metamodell: vedlegg/Informasjonstjeneste-meta.md
      - Deltakere i dialogmøter: vedlegg/Dialogmoter.md
    - Innspill til målarkitekturen:
      - innspill/index.md
      - Status for dokumentet: https://direktoratet-for-e-helse.github.io/Common-metadata/
theme:
  name: material
  logo: logo/ehelse-hvit.svg
  #custom_dir: material/.overrides
  features:
    # - navigation.path #sponsorfeature
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/git-alt
  favicon: logo/ehelse-hvit.png
markdown_extensions:
  - mdx_truly_sane_lists
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  #icon:
  #  logo: logo
plugins:
  - search
  - git-revision-date-localized:
      type: datetime
  - with-pdf:
      cover_subtitle: "currentbuild"
      copyright: ""
      # two_columns_level: 3
      output_path: ./pdf/malarkitektur.pdf